ComputerStore/Controllers/ManagerAccountController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Models;

namespace ComputerStore.Controllers
{
    public class ManagerAccountController : Controller
    {
        private ComputerStoreEntities db = new ComputerStoreEntities();

        // GET: ManagerAccount
        public ActionResult Index()
        {
            return View(db.Accounts.ToList());
        }

        // GET: ManagerAccount/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: ManagerAccount/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ManagerAccount/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Username,Password")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Accounts.Add(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: ManagerAccount/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: ManagerAccount/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Username,Password")] Account account)
        {
            if (ModelState.IsValid)
            {
                db.Entry(account).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(account);
        }

        // GET: ManagerAccount/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // POST: ManagerAccount/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Account account = db.Accounts.Find(id);
            db.Accounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ComputerStore/Controllers/ManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Models;
using System.Net;

namespace ComputerStore.Controllers
{
    public class ManagerController : Controller
    {
        ComputerStoreEntities db = new ComputerStoreEntities();
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
    }
}

ComputerStore/Controllers/ManagerSanPhamController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Models;

namespace ComputerStore.Controllers
{
    public class ManagerSanPhamController : Controller
    {
        private ComputerStoreEntities db = new ComputerStoreEntities();

        // GET: ManagerSanPham
        public ActionResult Index()
        {
            var chiTietSPs = db.ChiTietSPs.Include(c => c.ChiTietNSX).Include(c => c.SanPham);
            return View(chiTietSPs.ToList());
        }

        // GET: ManagerSanPham/Details/5
        public ActionResult Details(string _id)
        {
            if (_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietSP chiTietSP = db.ChiTietSPs.Find(_id);
            if (chiTietSP == null)
            {
                return HttpNotFound();
            }
            return View(chiTietSP);
        }

        // GET: ManagerSanPham/Create
        public ActionResult Create()
        {
            ViewBag.MaNSX = new SelectList(db.ChiTietNSXes, "MaNSX", "TenNSX");
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "MaSP");
            return View();
        }

        // POST: ManagerSanPham/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaSP,TenSP,MaNSX,CPU,RAM,HDD,Screen,DonGia")] ChiTietSP chiTietSP, HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength == 0)
            {
                ModelState.AddModelError("", "Chưa chọn hình");
            }
            else
            {
                string extend = System.IO.Path.GetExtension(file.FileName);
                if (extend != ".jpg" && extend != ".jpeg" && extend != ".png")
                {
                    ModelState.AddModelError("", "Hình ảnh phải có đuôi .jpg hoặc .jpeg hoặc .png");
                }
                else
                {
                    chiTietSP.Anh = chiTietSP.MaSP + extend;
                    try
                    {
                        file.SaveAs(Server.MapPath("~/Content/Images/" + chiTietSP.Anh));
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Xảy ra lỗi khi lưu hình");
                    }
                }
            }
            if (ModelState.IsValid)
            {
                db.ChiTietSPs.Add(chiTietSP);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNSX = new SelectList(db.ChiTietNSXes, "MaNSX", "TenNSX", chiTietSP.MaNSX);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "MaSP", chiTietSP.MaSP);
            return View(chiTietSP);
        }

        // GET: ManagerSanPham/Edit/5
        public ActionResult Edit(string _id)
        {
            if (_id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietSP chiTietSP = db.ChiTietSPs.Find(_id);
            if (chiTietSP == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNSX = new SelectList(db.ChiTietNSXes, "MaNSX", "TenNSX", chiTietSP.MaNSX);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "MaSP", chiTietSP.MaSP);
            return View(chiTietSP);
        }

        // POST: ManagerSanPham/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,MaNSX,CPU,RAM,HDD,Screen,DonGia")] ChiTietSP chiTietSP, HttpPostedFileBase file)
        {
            if (file == null || file.ContentLength == 0)
            {
                ModelState.AddModelError("", "Chưa chọn hình");
            }
            else
            {
                string extend = System.IO.Path.GetExtension(file.FileName);
                if (extend != ".jpg" && extend != ".jpeg" && extend != ".png")
                {
                    ModelState.AddModelError("", "Hình ảnh phải có đuôi .jpg hoặc .jpeg hoặc .png");
                }
                else
                {
                    chiTietSP.Anh = chiTietSP.MaSP + extend;
                    try
                    {
                        file.SaveAs(Server.MapPath("~/Content/Images/" + chiTietSP.Anh));
                    }
                    catch
                    {
                        ModelState.AddModelError("", "Xảy ra lỗi khi lưu hình");
                    }
                }
            }

            if (ModelState.IsValid)
            {
                db.Entry(chiTietSP).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNSX = new SelectList(db.ChiTietNSXes, "MaNSX", "TenNSX", chiTietSP.MaNSX);
            ViewBag.MaSP = new SelectList(db.SanPhams, "MaSP", "MaSP", chiTietSP.MaSP);
            return View(chiTietSP);
        }

        // GET: ManagerSanPham/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChiTietSP chiTietSP = db.ChiTietSPs.Find(id);
            if (chiTietSP == null)
            {
                return HttpNotFound();
            }
            return View(chiTietSP);
        }

        // POST: ManagerSanPham/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            ChiTietSP chiTietSP = db.ChiTietSPs.Find(id);
            db.ChiTietSPs.Remove(chiTietSP);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ComputerStore/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ComputerStore.Models;

namespace ComputerStore.Controllers
{
    public class SanPhamController : Controller
    {
        ComputerStoreEntities db = new ComputerStoreEntities();

        // GET: ViewDetail
        public ActionResult ViewDetails(string _id)
        {
            ChiTietSP sanphamDC = db.ChiTietSPs.FirstOrDefault(m => m.MaSP == _id);
            if (sanphamDC == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(sanphamDC);
        }

        public ActionResult OrderBrand(string _idname)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.MaNSX.Contains(_idname));
            return View();
        }
        public ActionResult OrderPrice(int _min, int _max)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            if (_max == 0)
            {
                ViewBag.sanphams = db.ChiTietSPs.Where(m => m.DonGia > _min);
                return View();
            }
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.DonGia > _min && m.DonGia < _max);
            return View();
        }
        public ActionResult OrderCPU(string _name)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.CPU.Contains(_name));
            return View();
        }
        public ActionResult OrderHDD(string _size)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.HDD.Contains(_size));
            return View();
        }
        public ActionResult OrderScreen(string _size)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.Screen.Contains(_size));
            return View();
        }
        public ActionResult OrderRAM(string _size)
        {
            ViewBag.nhasanxuats = db.ChiTietNSXes;
            ViewBag.sanphams = db.ChiTietSPs.Where(m => m.RAM.Contains(_size));
            return View();
        }
    }
}

ComputerStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using ComputerStore.Models;
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Laptop Tiến Thành", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>
                        <a href="@Url.Action("Index", "GioHang")">
                            @if (Session["GioHang"] == null)
                            {
                                <span>0</span>
                            }
                            else
                            {
                                <span>
                                    ( @((Session["GioHang"] as List<GioHang>).Sum(m => m.iSoLuong)) )
                                </span>
                            }
                            &nbsp;<span class="glyphicon glyphicon-shopping-cart"></span>
                        </a>
                    </li>
                </ul>
                <div class="col-md-4">
                    <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" />
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-nav">
                    <li><a>Sign up</a></li>
                    <li><a href="@Url.Action("Login", "Manager")">Sign in</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <br />
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ThanhPTg</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ComputerStore/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/Admin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/Admin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/Admin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Content/Admin/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/Admin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Laptop Tiến Thành</a>
            </div>
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Login", "Manager")"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li class="sidebar-search">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index", "Manager")"><i class="fa fa-dashboard fa-fw"></i> Tổng quan</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-database fa-fw"></i> Quản lý<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="@Url.Action("Index", "ManagerSanPham")"> Sản phẩm</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("Index", "ManagerHoaDonNhap")"> Đơn hàng</a>
                                </li>
                                <li>
                                    <a href="#"> Nhà cung cấp</a>
                                </li>
                                <li>
                                    <a href="#"> Khách hàng</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                        <li>
                            <a href="@Url.Action("Index","ManagerAccount")"><i class="fa fa-users fa-fw"></i> Tài khoản</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">@ViewBag.Title</h1>
                </div>
                <!-- /.col-lg-12 -->
                @RenderBody()
            </div>
            <!-- /#page-wrapper -->
        </div>
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Content/Admin/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/Admin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/Admin/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Content/Admin/vendor/raphael/raphael.min.js"></script>
    <script src="~/Content/Admin/vendor/morrisjs/morris.min.js"></script>
    <script src="~/Content/Admin/data/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/Admin/dist/js/sb-admin-2.js"></script>
</body>
</html>

ComputerStore/Views/Shared/_LayoutMain.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Laptop Tiến Thành", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li><a href="@Url.Action("Index", "GioHang")">
                        @if (Session["GioHang"] == null)
                        {
                            <span>0</span>
                        }
                        else
                        {
                            <span>
                                ( @((Session["GioHang"] as List<GioHang>).Sum(m => m.iSoLuong)) )
                            </span>
                        }
                        &nbsp;<span class="glyphicon glyphicon-shopping-cart"></span>
                    </a></li>
                </ul>
                <div class="col-md-4">
                    <form class="navbar-form" role="search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search" />
                            <div class="input-group-btn">
                                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                            </div>
                        </div>
                    </form>
                </div>
                <ul class="nav navbar-nav">
                    <li><a>Sign up</a></li>
                    <li><a href="@Url.Action("Login", "Manager")">Sign in</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div class="row">
            <div class="jumbotron">
                <h1>Bootstrap Tutorial</h1>
                <p>Bootstrap is the most popular HTML, CSS, and JS framework for developing responsive, mobile-first projects on the web.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-md-9">
                @RenderBody()
            </div>
            <div class="col-md-3">
                <div>
                    <div class="list-group-item-heading">HÃNG SẢN XUẤT</div>
                    <ul class="list-group">
                        @using ComputerStore.Models;
                        @foreach (ChiTietNSX nhasx in ViewBag.nhasanxuats)
                        {
                            <li class="list-group-item"><a href="@Url.Action("OrderBrand","SanPham", new { _idname = nhasx.MaNSX})">@nhasx.TenNSX</a></li>
                        }
                    </ul>
                </div>
                <div>
                    <div class="list-group-item-heading">KHOẢNG GIÁ</div>
                    <ul class="list-group">
                        <li class="list-group-item"><a href="@Url.Action("OrderPrice","SanPham", new { _min = 0, _max = 10000000})">dưới 10 triệu</a></li>
                        <li class="list-group-item"><a href="@Url.Action("OrderPrice","SanPham", new { _min = 10000000, _max = 14000000})">10 - 14 triệu</a></li>
                        <li class="list-group-item"><a href="@Url.Action("OrderPrice","SanPham", new { _min = 14000000, _max = 18000000})">14 - 18 triệu</a></li>
                        <li class="list-group-item"><a href="@Url.Action("OrderPrice","SanPham", new { _min = 20000000, _max = 0})">trên 20 triệu</a></li>
                    </ul>
                </div>
                <div>
                    <div class="list-group-item-heading">LỌC SẢN PHẨM</div>
                    <div>
                        <div class="list-group-item-heading">CPU</div>
                        <ul class="list-group">
                            <li class="list-group-item"><a href="@Url.Action("OrderCPU","SanPham", new { _name = "i7"})">Intel Core i7</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderCPU","SanPham", new { _name = "i5"})">Intel Core i5</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderCPU","SanPham", new { _name = "i3"})">Intel Core i3</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderCPU","SanPham", new { _name = "Pentium"})">Intel Pentium</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderCPU","SanPham", new { _name = "Celeron"})">Intel Celeron</a></li>
                        </ul>
                    </div>
                    <div>
                        <div class="list-group-item-heading">HDD</div>
                        <ul class="list-group">
                            <li class="list-group-item"><a href="@Url.Action("OrderHDD", "SanPham", new { _size ="500GB"})">500GB</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderHDD", "SanPham", new { _size ="1TB"})">1TB</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderHDD", "SanPham", new { _size ="2TB"})">2TB</a></li>
                        </ul>
                    </div>
                    <div>
                        <div class="list-group-item-heading">RAM</div>
                        <ul class="list-group">
                            <li class="list-group-item"><a href="@Url.Action("OrderRAM", "SanPham", new { _size ="4GB"})">4GB</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderRAM", "SanPham", new { _size ="8GB"})">8GB</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderRAM", "SanPham", new { _size ="16GB"})">16GB</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderRAM", "SanPham", new { _size ="32GB"})">32GB</a></li>
                        </ul>
                    </div>
                    <div>
                        <div class="list-group-item-heading">MÀN HÌNH</div>
                        <ul class="list-group">
                            <li class="list-group-item"><a href="@Url.Action("OrderScreen", "SanPham", new { _size ="14"})">14"</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderScreen", "SanPham", new { _size ="15"})">15.6"</a></li>
                            <li class="list-group-item"><a href="@Url.Action("OrderScreen", "SanPham", new { _size ="17"})">17"</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - ThanhPTg</p>
            </footer>
        </div>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>